// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM7EO9lobavrTuNg335w6O2o8HX5wrGqA',
    appId: '1:109550902306:web:f3deb8a17e3773ffc27e7b',
    messagingSenderId: '109550902306',
    projectId: 'av-volunteer-app',
    authDomain: 'av-volunteer-app.firebaseapp.com',
    storageBucket: 'av-volunteer-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-W2eGZk2DUC8pAoEWi1mavjaVqmQxOpQ',
    appId: '1:109550902306:android:00913a84ee6e1568c27e7b',
    messagingSenderId: '109550902306',
    projectId: 'av-volunteer-app',
    storageBucket: 'av-volunteer-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJlAmK1xyRdREXfRCkD9_j8foKTAEzda0',
    appId: '1:109550902306:ios:1baf628b8e1c0069c27e7b',
    messagingSenderId: '109550902306',
    projectId: 'av-volunteer-app',
    storageBucket: 'av-volunteer-app.firebasestorage.app',
    iosBundleId: 'com.example.avVolunteerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJlAmK1xyRdREXfRCkD9_j8foKTAEzda0',
    appId: '1:109550902306:ios:1baf628b8e1c0069c27e7b',
    messagingSenderId: '109550902306',
    projectId: 'av-volunteer-app',
    storageBucket: 'av-volunteer-app.firebasestorage.app',
    iosBundleId: 'com.example.avVolunteerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM7EO9lobavrTuNg335w6O2o8HX5wrGqA',
    appId: '1:109550902306:web:10e77dca1bf0c8bdc27e7b',
    messagingSenderId: '109550902306',
    projectId: 'av-volunteer-app',
    authDomain: 'av-volunteer-app.firebaseapp.com',
    storageBucket: 'av-volunteer-app.firebasestorage.app',
  );
}
